services:
  - type: redis
    name: supallama-ai-web-redis
    region: oregon
    plan: starter # use a plan with persistence
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
  - type: web
    runtime: node
    name: supallama-ai-web-ui
    region: oregon
    repo: https://github.com/SupaLlama/supallama-ai-frontend 
    buildCommand: "npm install; npm run build" 
    startCommand: "npm run start"
    domains:
      - supallama.ai
      - www.supallama.ai
    envVars:
      - key: SUPALLAMA_AI_API
        value: http://supallama-ai-web-workers-fastapi:10000
      - fromGroup: supallama-frontend-env-vars
  - type: pserv 
    runtime: python
    name: supallama-ai-web-workers-fastapi
    region: oregon
    repo: https://github.com/SupaLlama/supallama-ai-web-workers
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: supallama-ai-web-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_URL
        fromService:
          name: supallama-ai-web-redis
          type: redis
          property: connectionString
      - fromGroup: supallama-backend-env-vars
  - type: worker
    name: supallama-ai-web-workers-celery-worker
    region: oregon
    runtime: python
    repo: https://github.com/SupaLlama/supallama-ai-web-workers
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A main.celery worker --loglevel=info --concurrency 2"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: supallama-ai-web-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_URL
        fromService:
          name: supallama-ai-web-redis
          type: redis
          property: connectionString
      - fromGroup: supallama-backend-env-vars
  # Flower doesn't yet support Celery 5.x
  # - type: web
  #   name: supallama-ai-web-workers-celery-flower
  #   region: oregon
  #   plan: free
  #   runtime: python
  #   repo: https://github.com/SupaLlama/supallama-ai-web-workers
  #   buildCommand: "pip install -r requirements.txt"
  #   startCommand: "celery flower -A main.celery --loglevel info"
  #   envVars:
  #     - key: CELERY_BROKER_URL
  #       fromService:
  #         type: redis
  #         name: supallama-ai-web-redis
  #         property: connectionString
