services:
  - type: redis
    name: supallama-ai-web-redis
    region: oregon
    plan: starter # use a plan with persistence
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
  - type: web
    runtime: node
    name: supallama-ai-web-ui
    region: oregon
    repo: https://github.com/SupaLlama/supallama-ai-web-ui
    buildCommand: "npm install; npm run build" 
    startCommand: "npm run start"
    domains:
      - supallama.ai
      - www.supallama.ai
    envVars:
      - key: SUPALLAMA_AI_API
        fromService:
          name: supallama-ai-web-workers-fastapi
          type: pserv
          envVarKey: RENDER_INTERNAL_URL
  - type: pserv 
    runtime: python
    name: supallama-ai-web-workers-fastapi
    region: oregon
    repo: https://github.com/SupaLlama/supallama-ai-web-workers
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: supallama-ai-web-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_URL
        fromService:
          name: supallama-ai-web-redis
          type: redis
          property: connectionString
  - type: worker
    name: supallama-ai-web-workers-celery-worker
    region: oregon
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: supallama-ai-web-redis
          type: redis
          property: connectionString
  - type: web
    name: supallama-ai-web-workers-celery-flower
    region: oregon
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: supallama-ai-web-redis
          property: connectionString
